# Generated by Django 4.2.6 on 2023-11-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=50)),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=20)),
                ('seat_type', models.CharField(max_length=10)),
                ('seat_comfort', models.IntegerField()),
                ('cabin_crew', models.IntegerField()),
                ('ground_service', models.IntegerField()),
                ('review', models.TextField()),
                ('result', models.CharField(max_length=5)),
            ],
        ),
    ]
